my-cluster:
  Type: AWS::Cluster

  Configuration:
    BakeInstance:
      Properties:
        ImageId:
          Fn::Pipeline::ImageId:
            Name: amazon-linux
        InstanceType: t3.medium

    AutoScalingGroup:
      Pipeline::Security:
        - Allow: TCP:22
          Source: bastion
        - Allow: TCP:80
          Source: intranet
      CreationPolicy:
        AutoScalingCreationPolicy:
          MinSuccessfulInstancesPercent: 75
      Properties:
        Cooldown: 300
        HealthCheckGracePeriod: 900
        MinSize: 2
        MaxSize: 4

    LaunchConfiguration:
      Properties:
        InstanceType: t3.medium

    ScaleDownScalingPolicy:
      Properties:
        AdjustmentType: ChangeInCapacity
        Cooldown: 60
        PolicyType: SimpleScaling
        ScalingAdjustment: -1

    ScaleUpScalingPolicy:
      Properties:
        AdjustmentType: ChangeInCapacity
        Cooldown: 300
        PolicyType: SimpleScaling
        ScalingAdjustment: 1

    HighCpuAlarm:
      Properties:
        AlarmActions:
          - Ref: ScaleUpScalingPolicy
        ComparisonOperator: GreaterThanThreshold
        EvaluationPeriods: 2
        MetricName: CPUUtilization
        Period: 60
        Statistic: Average
        Threshold: 75

    LowCpuAlarm:
      Properties:
        AlarmActions:
          - Ref: ScaleDownScalingPolicy
        ComparisonOperator: LessThanThreshold
        EvaluationPeriods: 4
        MetricName: CPUUtilization
        Period: 60
        Statistic: Average
        Threshold: 35