my-bucket:
  Type: AWS::S3::Bucket
  Persist: true

  Configuration:
    Bucket:
      Pipeline::Security:
        - Allow: [list, read, write, delete]
          Source: my-instance
      Properties:
        VersioningConfiguration:
          Status: Enabled