mysecret1:
  Type: AWS::SecretsManager::Secret
  Persist: true
  Configuration:
    Secret:
      Properties:
        GenerateSecretString:
          SecretStringTemplate: "\"{\\\"username\\\": \\\"myusername\\\"}\""
