my-lambda:
  Type: AWS::Serverless
  Persist: false

  Configuration:
    Function:
      Properties:
        Code:
          S3Key:
            Fn::Pipeline::FileS3Key:
              Path: dynamo-writer-lambda.zip
        Handler: main.handler
        MemorySize: 128
        Runtime: python3.6
        Timeout: 3
        Environment:
          Variables:
            BUILD: "{{ context.Build }}"
            RDS_ENDPOINT: "{{ vars.RdsHostName }}"
            HTTPS_PROXY: "{{ context.ProxyUrl }}"
